"task":
  "task_type" : "regression" #vs. control
  "function_set": ["&", "|", "mov", "~", "identity"]
  "arity": {"|" : 2, "&": 2,  "~" : 1, "mov" : 1, "identity" : 1}
  #could be wrong about this but assuming here data just means writeable
  "num_data_registers": 7
  "output_registers": [6]
  "num_registers": 7
  "dataset" : "task/6-bit-parity.csv" #this is a series of inputs X and outputs Y (mixed arity)
  "constraints": []
  "sequence_length": 100

"policy_gradient_algo":
    "gamma": 0.99
    "batch_size": 512
    "entropy_beta": 9
    "avg_reward_len": 1
    "epoch_len": 2048
    "lr_actor": 3e-4
    "lr_critic": 1e-3
    "nb_optim_iters": 4
    "clip_ratio": 0.2
